### ISSUE TITLE
Game Request: DATE A LIVE: Rio Reincarnation

### ISSUE THREAD

**Issue by Arata12** [marcussacana/Specific-Games#10]
Hi, I’m interested in translating this game.
Do you think SRL will work on this game?

**Comment by marcussacana** [comment]
No idea, I'm planning buy the game but not sure yet.

**Comment by Arata12** [comment]
I see, anyway thanks for answering

**Comment by marcussacana** [comment]
Take a look: https://github.com/thesupersonic16/DALTools

**Comment by marcussacana** [comment]
@Arata12 Date A Live Added, any bug you can open the issue again.

**Comment by Arata12** [comment]
could you update the .exe? the original one (1.00.00) has some bugs, they already solved. the latest version is 1.00.02.

**Comment by marcussacana** [comment]
If you can upload the new version to me and send to my email, yes, but will take a time

**Comment by Arata12** [comment]
The whole game? or just the .exe? I mean, I think you can work with the "old" version and only replace the .exe, If you need the whole game, I can upload it in some days. I'll attach the .exe 


[DATE A LIVE RIO-REINCARNATION.zip](https://github.com/marcussacana/Specific-Games/files/4373102/DATE.A.LIVE.RIO-REINCARNATION.zip)

**Comment by marcussacana** [comment]
If work well, whatever, I will left this issue open and I will take a look when I have time

**Comment by Arata12** [comment]
Okay, thx.

**Comment by marcussacana** [comment]
Your request is the next in my queue. I will check soon.

**Comment by marcussacana** [comment]
@Arata12 Added, Looks like you're AFK, then I will close the issue to you, if you found any problem you can open it again
