### ISSUE TITLE
Hello, Goodbye. Patch files not working

### ISSUE THREAD

**Issue by imKota** [marcussacana/Specific-Games#11]
Hello, @marcussacana !

Patch files not working :c

**Comment by marcussacana** [comment]
Hmm, show what file you moddifed and where you saved

**Comment by imKota** [comment]
I create file with name "DEBUG" in the HGN_Data directory, start the game. All files unpacked corrected.


open 00.txt

![image](https://user-images.githubusercontent.com/24241471/61999217-f01cab00-b0c4-11e9-95fa-4e0ae4254623.png)

edited text
![image](https://user-images.githubusercontent.com/24241471/61999219-fad74000-b0c4-11e9-89b7-ba026dcad975.png)

launch game and..
1. russian text not working:c
![image](https://user-images.githubusercontent.com/24241471/61999255-923c9300-b0c5-11e9-978f-4e11576dff5d.png)

2. The date the file was changed has not changed.
![image](https://user-images.githubusercontent.com/24241471/61999275-00815580-b0c6-11e9-8f12-e500beb924d7.png)


3. Modified files are read from folders.

The original files have not changed.
If you delete folders, the text will be the same as before the changes in unpacked files.

**Comment by imKota** [comment]
@marcussacana it's normal? :DD

**Comment by marcussacana** [comment]
You tried use latin characters? by your screenshot I think is because the game font don't include the russian characters, then the game can't dispaly the text.
![image](https://user-images.githubusercontent.com/10576957/61999454-acf81300-b097-11e9-8953-865bc78cebd7.png)

**Comment by marcussacana** [comment]
About the script.dat don't change, this is right, my mod don't repack, he just make the game accept the files externally.

**Comment by imKota** [comment]
Hmmm. Maybe you know how to add support russian characters in this game ?

**Comment by marcussacana** [comment]
Sorry but this is more hard, I think you will need found someone who understand the unity engine better than me to this.

**Comment by imKota** [comment]
> unity engine

xDD

I have problems with him too. It is easier for me to download the old release, which is not on unity and use it.

**Comment by imKota** [comment]
@marcussacana maybe you know how to change font ???

**Comment by marcussacana** [comment]
It's around this class, but I never tried to say. (UIAdv)
![image](https://user-images.githubusercontent.com/10576957/61999508-d7969b80-b098-11e9-9995-7cd4b55f6b5f.png)

**Comment by imKota** [comment]
> It's around this class, but I never tried to say. (UIAdv)
> ![image](https://user-images.githubusercontent.com/10576957/61999508-d7969b80-b098-11e9-9995-7cd4b55f6b5f.png)

Thanks :3

**Comment by marcussacana** [comment]
Take a look in this too
https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor

**Comment by imKota** [comment]
> Take a look in this too
> https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor

![image](https://user-images.githubusercontent.com/24241471/61999524-9ff51700-b0cb-11e9-84c9-688af3d38d03.png)
