### ISSUE TITLE
About The Witch's Love Diary

### ISSUE THREAD

**Issue by Cerzs** [marcussacana/Specific-Games#13]
Hi! I was checking the new feature, congrats, it works great! 

I just noticed that +18 DLC... is not included in strings? How can I dump it without breaking everything? lol

Also, do you know any tool for those prologue images? I was looking, but no luck.

Thanks.

**Comment by marcussacana** [comment]
To create a .lst dump, you can use my [TLBOT](https://github.com/marcussacana/TLBOT), extract the TEXT.DAT using my UnionShiftManager (Don't works with other extractors) and install the sacanawrapper plugin to open the SoftPal script, then in the TLBOT change the client to Cache Only and check the "LST Mode"
![image](https://user-images.githubusercontent.com/10576957/64070724-89982900-cc3e-11e9-9e33-8be983de7401.png)
Then add the TEXT.DAT and the LST will be generated.
![image](https://user-images.githubusercontent.com/10576957/64070721-666d7980-cc3e-11e9-92a2-e96b69ab1a83.png)

About the Image, hmm, You tried the GARBro?

**Comment by Cerzs** [comment]
It seems that my TLBOT is outdated, I don't have VS here so I'll try later. Thx.

GARBro can open the images, yes. But that format does not need unpack/repack?

![imagen](https://user-images.githubusercontent.com/44489935/64070953-c19e6c80-cc3c-11e9-95df-d4c621e33bcb.png)

**Comment by marcussacana** [comment]
This engine support PNG images, you can just use the GARBro to extract, then change the extension to .pgd and replace the original image.
![image](https://user-images.githubusercontent.com/10576957/64073349-e281b480-cc72-11e9-9312-7276506446d1.png)

**Comment by Cerzs** [comment]
Wow, it works. Thank you, @marcussacana! Btw, if you can add the latest compiled version of TLBOT would be amazing... I told a friend to compile it and he was getting errors, but he had to go somewhere and we couldn't check it.

Also, maybe you want to update Ley-Line to the new feature. And if you accept sugestions, I would say that exHIBIT or Minori needs it, those engine are really a pain, but idk.

Anyway, thanks again! See you!

**Comment by marcussacana** [comment]
@Cerzs I published the lastest build of the TLBOT, take a look.

**Comment by Cerzs** [comment]
Hi, @marcussacana. I tried what you told me. I think I'm doing it wrong, the generated .lst is only 400 kb with about 7k lines. I was checking the "database" tab but same result.

If you wanna check, [here's the text.dat](https://cdn.discordapp.com/attachments/475037213265100820/618161027162439693/tex2.zip).

![imagen](https://user-images.githubusercontent.com/44489935/64131229-3f758b80-cd95-11e9-83f0-ef86379299e1.png)

**Comment by marcussacana** [comment]
Disable this and restart the TLBOT
![image](https://user-images.githubusercontent.com/10576957/64133903-026ac280-cdb0-11e9-8cd8-e39b116e7b26.png)

**Comment by Cerzs** [comment]
Is it normal that the only generated file to be this? 1 MB now.

![imagen](https://user-images.githubusercontent.com/44489935/64134308-bcf7c680-cdaa-11e9-807e-a0a758310a3f.png)

**Comment by marcussacana** [comment]
they don't created the .lst in the original script directory?
that .tbc file can be used with the SRL but isn't the best option.
if you want use the TLBOT-EN.tbc with the SRL, rename to Strings.srl and replace the database, then enable the "Dump" in the SRL.ini, but I really don't recommend this, the TLBOT can create the .lst, that is the best option.

**Comment by Cerzs** [comment]
I selected the file and configured like you said, after analyzing it just keep "idle" but no files created.

**Comment by marcussacana** [comment]
I think you did something wrong, but forget then, Try the 'LST Generator' tool [here](https://github.com/marcussacana/StringReloads/tree/master/Help)
Have a readme inside the 7z, take a look too.

**Comment by Cerzs** [comment]
Lol, I'm really bad at this. Sorry about that! Yes, that works perfect. Thanks.
