### ISSUE TITLE
Game Request: Aokana -Four Rhythms Across the Blue-

### ISSUE THREAD

**Issue by meteoro07** [marcussacana/Specific-Games#14]
I would like to translate this game. (English version)
I think it uses the same engine as Hello, Goodbye (English version).

**Comment by marcussacana** [comment]
I already did the mod to this game, but afraid of causing legal problems, I never published.
If you really want translate it and can prove that, I can send the required to translate to you in a private way, by now, try contact me in email or discord Marcus André#0956
