### ISSUE TITLE
Request Sayonara o Oshiete ~Comment te Dire Adieu~

### ISSUE THREAD

**Issue by Tfausx** [marcussacana/Specific-Games#16]
Hello Marcus, i hope you're having a nicely day, i was wondering if it possible to make a tools for this game:

Sayonara o Oshiete ~Comment te Dire Adieu~ (download edition), it is a really good denpa game (there's not too much vn's with that genre). Aside of that, the game have two releases (normal) and and updated release (Win7 + supports), this new release uses Siglus Engine! I will give you the script where's the text located (if you need the whole game, i can upload it too)

https://drive.google.com/file/d/1h70hmchaMYinuGp1mjTUt-iXVKQ_EpyJ/view?usp=sharing

Thanks in advance!

**Comment by marcussacana** [comment]
Use this tool: https://github.com/marcussacana/SiglusSceneManager
What here how: https://www.youtube.com/watch?v=jYc-uxZRsIg

**Comment by Tfausx** [comment]
Everything works perfect, thanks again for you hard work, you're really awesome man! But i have a problem, when i repack the game, doesn't recognize the new translation (in-game scrips) but the scripts of days (game shows you in the bottom of the window a name of the days of the game) are recognized with the translation.

I sent you an screenshot so you can understand better what i say

https://i.ibb.co/685v7mC/1.png

You have any idea why this happens?

Thanks again for all!

**Comment by marcussacana** [comment]
No idea, srry.

**Comment by Tfausx** [comment]
Fixed, was a mistake from my part xD, sorry for the trouble and again thanks for all! Have a nice day!
