### ISSUE TITLE
Game request:  Adabana Itan

### ISSUE THREAD

**Issue by SrDoggo0001** [marcussacana/Specific-Games#17]
Hello, I hope you're having a nice day!

I would like to know if there are or could you develop tools for Adabana Itan aka Adabana Odd Tales. The engine is Silky Engine.
I don't know if you need any more info about the game, I'm relatively new with VNs. Sorry for the inconvenience. 

Thank you in advance!

**Comment by marcussacana** [comment]
Read this https://github.com/marcussacana/SacanaWrapper/issues/7

--Edit
Looks like the creator of the issue deleted it for some reason, new link:
http://web.archive.org/web/20201110064318/https://github.com/marcussacana/SacanaWrapper/issues/7

**Comment by SrDoggo0001** [comment]
Thanks, man. I'll check it out.
