### ISSUE TITLE
Game Request: Kara no Shoujo - The Last Episode (Help only with font)

### ISSUE THREAD

**Issue by Tfausx** [marcussacana/Specific-Games#20]
Hello marcus, i hope you're having a good night! I was wondering if you can give me a hand with the font of this game to add special characters with special font modified, the engine used in the game it's "Innocent Grey Engine" with .iga format for the archives and .s for the texts.

I was investigating the game and the only archive realated to a "Font" it's a .dll inside of plugin folder of the game:

![imagen](https://user-images.githubusercontent.com/29191836/108023642-bcd0a280-7001-11eb-9ea9-20c3e6bac47a.png)

So has i say in the first part of the reply, could be possible give me a hand with a way to ¿modify? or mod the font of the game to replace with other

If you need the game or the tools to extract the .iga or .s, i can sent it all with a PM!

Thanks in advance and have a good day!

**Comment by marcussacana** [comment]
Innocent Grey - I can't work with this engine, sorry

**Comment by CrAZONE0** [comment]
@Tfausx Sorry, this is unrelated to your question. But how did you decrypt KnS3's .s files? I tried the igscript tool but it gave me empty .txt files
