### ISSUE TITLE
Game Request : [Guilty] Toriko no Kusari

### ISSUE THREAD

**Issue by watanuki88** [marcussacana/Specific-Games#21]
Hello, I really need help for this.

I have tried to use String Reloads with Auto Install and I made two changes in the .ini files that is AutoInstall to true and Shift-JIS to utf-18 since this game's engine is willplus AdvHD.

I changed the name of dll to be d3d9.dll but when I run the game, after passed the graphic setting dialog, the game force closed without warning while leaving a dump file and StringReloads folder with Cache.srl file inside of it.

Where did i do wrong? I use x86 stringreloads and  run it on windows 10 x64.

I also tried to rename the dll name using the names on the wrapper page but most of it didn't work at all despite the game run properly and some have the same results as d3d9.dll did.

Thank you for the help.

**Comment by marcussacana** [comment]
Sorry but I can't work with games of this engine.
