### ISSUE TITLE
About Fraternite

### ISSUE THREAD

**Issue by Tfausx** [marcussacana/Specific-Games#23]
Hi Marcus! I hope you're having a great day! I have one question about Fraternite, i was checking the .lst scripts in the StringReloader folder and i can't found the first dialogues of the game, then i start the game i see there's a Strings.lst single file who "takes" all the texts of the game of the part you're already played. My question is, in order to translate the game, first i need to finish the whole game (read)?

Thanks in advance!

**Comment by marcussacana** [comment]
Ohh, that a old title, I really don't remember, but if my dump missed lines, you really can just run the game to force dump.
If isn't a jrpg then you can just skip the whole game and the Strings.lst will be created, isn't like you need to read it.

**Comment by Tfausx** [comment]
Yeah, it's not a JRPG, it's a visual novel who uses YU-RIS engine, and yeah, i also try to modify the dumped Strings.lst with the translation, but the game doesn't seems to recognize the changes xD

In any case, if you don't remember nothing about this, no problem!
