### ISSUE TITLE
 problem with the kirikiri text box

### ISSUE THREAD

**Issue by MyWork1908** [marcussacana/Specific-Games#24]
Sorry for asking an unrelated issue. But I see you know quite well.

![Ảnh chụp màn hình (170)_LI](https://user-images.githubusercontent.com/68116972/117571816-53d96200-b0fa-11eb-87b2-5b99c8cc49de.jpg)

The above sentence is: "Hẳn mọi người tò mò về tên game phải không? Nhưng mà trước khi vào cốt truyện thì để tôi giới thiệu qua về em gái tôi cái đã."

the word "Không?" is not a line break as it is a single word!

I want it to line up only when a space is available

I can't edit the text box because the tjs files are encrypted

here is data.xp3 file: https://drive.google.com/file/d/1HSdKUDKaWozRZIYfTs4FYA25Q1tqUKg1/view?usp=sharing

please help me!

**Comment by marcussacana** [comment]
Try this method: https://lv1translator.wordpress.com/2014/05/15/word-wrapping-code-upload/

**Comment by MyWork1908** [comment]
I should replace mainwindow.tjs file into data.xp3 or put in patch.xp3
Have you seen data.xp3 file? it is encrypted.
name game: My.Little.Sister.Cant.Possibly.Have.a.Hemorrhoid

**Comment by marcussacana** [comment]
patch.xp3 is enought usually, but I don't think you can just replace, that is a example, you will need to see what they did to fix and apply the same changes in the original mainwindow.tjs of your game.

**Comment by MyWork1908** [comment]
but the tjs files are encrypted

![Ảnh chụp màn hình (170)](https://user-images.githubusercontent.com/68116972/117577774-7036c800-b115-11eb-8f00-b913af60b045.png)

**Comment by marcussacana** [comment]
Isn't encrypted, is compiled.
in this case will be hard to you do that alone, Sorry but I don't have time to do that as well,
What you can do is override the mainwindow instance to be able to modify the code.
