### ISSUE TITLE
Problem with the kirikiri text box 2

### ISSUE THREAD

**Issue by MyWork1908** [marcussacana/Specific-Games#25]
I found the tjs files are not compiled
it is here: https://drive.google.com/drive/folders/1j9_v3bdzS2iTc4GnBzVzCt3uJFBRid6d?usp=sharing

but now there are spaces between a word. that space is not present in the text file.

I edited many times but with no success.

![Ảnh chụp màn hình (181)_LI](https://user-images.githubusercontent.com/68116972/117686317-f23ff300-b1e0-11eb-8a39-f0f04acd6d4e.jpg)

**Comment by marcussacana** [comment]
looks like this problem occours only with special characters, try change to a monospaced font

**Comment by MyWork1908** [comment]
I tried changing the font but it didn't work
but you see this 

it is messageslayer:
![Ảnh chụp màn hình (191)](https://user-images.githubusercontent.com/68116972/118119085-0883c400-b418-11eb-8e1d-17720af0734a.png)

and it is Historylayer:
![Ảnh chụp màn hình (192)](https://user-images.githubusercontent.com/68116972/118119153-22bda200-b418-11eb-8a80-1e9abcbd38f3.png)

Historylayer doesn't give error like messageslayer.
I have redirected to edit messageslayer file but no success

**Comment by MyWork1908** [comment]
please help me

**Comment by marcussacana** [comment]
Not sure man

**Comment by MyWork1908** [comment]
I have found the solution. Thank you very much
