### ISSUE TITLE
 Request Shizuku Renewal Edition

### ISSUE THREAD

**Issue by Tfausx** [marcussacana/Specific-Games#26]
Hello Marcus, i hope you're having a nicely day, i was wondering if it possible to make a tools for this game:

Shizuku (renewal --remake-- edition),  I will give you the script and the font (if you need the whole game, i can upload it too)

The engine it's the same as used in all the "Leaf" games, i can open all the archives with garbro and the game recognizes the archives unpacked in the main folder, so it's not necesary do the pack again, the only problem are the .SDT encripted texts and the font with the weird extention.

[Shizuku.zip](https://github.com/marcussacana/Specific-Games/files/6565336/Shizuku.zip)

Thanks in advance!

**Comment by marcussacana** [comment]
if they use a custom font format will be hard, my time is very small to work with complex things, but I will take a look when I can
