### ISSUE TITLE
Unable to Launch Reminiscence

### ISSUE THREAD

**Issue by HoodedTissue** [marcussacana/Specific-Games#27]
Sorry if this is a stupid question but I can't seem to get Reminiscence to get past importing all of the StringReloader files. I've put all of the files from the reminiscence.rar file into my reminiscence game directory but after the game imports the script files I get an error that I can't read because all of the text is garbled up. It seems to be saying that I'm missing a .cfg file but I'm not sure where I could get it. I've tried using your MajiroStringEditor but everytime I try to open up the .mjo file nothing appears. Would you happen to know of a fix for either the MajiroStringEditor or the String Reloader? Thanks!
Heres an image of the error:
![img](https://user-images.githubusercontent.com/69287363/137433428-afe65985-bbe9-48a7-ad5c-46e5f886bb78.PNG)
Heres an image of the game directory:
![reminience](https://user-images.githubusercontent.com/69287363/137433440-48c09d53-5544-4206-92b8-1476fa6351dc.PNG)
!

**Comment by marcussacana** [comment]
read this http://web.archive.org/web/20201110064318/https://github.com/marcussacana/SacanaWrapper/issues/7
If I remeber well this game use this same engine, right?

**Comment by HoodedTissue** [comment]
> 
> 
> read this http://web.archive.org/web/20201110064318/https://github.com/marcussacana/SacanaWrapper/issues/7 If I remeber well this game use this same engine, right?

Hm, this issue thread seems to be about the Silky Engine which uses the .mes format for the script but Reminiscence uses the Majiro Engine which uses .mjo for the script format. Would I have to follow the patching guide mentioned in the issue thread?

**Comment by marcussacana** [comment]
Nop, I just forgot the engine, this engine is a pain to translate ineed... try this https://github.com/trigger-segfault/MajiroTools

**Comment by HoodedTissue** [comment]
> 
> 
> Nop, I just forgot the engine, this engine is a pain to translate ineed... try this https://github.com/trigger-segfault/MajiroTools

Thank you, I got it to work! The tool was unable to extract three of the scripts but I was able to extract the three with this instead: https://github.com/Inori/FuckGalEngine/tree/master/Majiro/mjdev
