### ISSUE TITLE
I Walk Among Zombies 

### ISSUE THREAD

**Issue by Gygarde** [marcussacana/Specific-Games#3]
Idk if this is the right place to ask. Is there a way for deal with the script.noa? (Repack)

https://vndb.org/v16802

**Comment by marcussacana** [comment]
Duplicate Request, I'm already working into this.
The .noa can be extract with this tool: https://github.com/morkt/GARbro
But have somes issues, i have reported to the tool creator and I keep waiting a response.
After this Just need a way to repack, I haven't looked into this for now.
