### ISSUE TITLE
Missing names

### ISSUE THREAD

**Issue by javiert239** [marcussacana/Specific-Games#31]
Hello Marcus, I hope you are well!

I tested the "Magical Mariage Lunatics" tool, and it works just fine.
However, there are three names I cannot translate, and neither can't find them in the scripts.
They are:
Yuuta's Father
Yuuta's Mother
Yuuna's Father

Also, I can't find the choices in the scripts, but if I write they manually, I can translate them without problema.
The issue is only with those three names.

Have any idea of what is the problema here?

**Comment by marcussacana** [comment]
Looks like more a bad script dump.
If you write the missing names manually they can be translated?

**Comment by javiert239** [comment]
No. I already tried write them manually but didn't work. 
Also, I used the rld manager to look for those names in all the scripts, but I just couldn't find them

**Comment by marcussacana** [comment]
what SRL version you're using? I'm not sure how old is my Magical Marriage version.
show me the version number or a screenshot of the SRL.ini

**Comment by javiert239** [comment]
I don't know which version of SRL is, but the last modification date was on 12/3/2019.
Here a cap of the configuration:
![image](https://user-images.githubusercontent.com/35937688/163449046-c7b74028-997a-4320-800d-2372e5180108.png)

I just tried the last version from here:
https://github.com/marcussacana/StringReloads/releases/tag/7.5.9

I replaced the SRLx32.dll file for the SRLWrapper.dll, and changed the name. Then replaced the SRL.ini for the most new, and activated the autoinstall function. And then the game crashes.
The log file doesn't show any error:
[INF] SRL - StringReloads v7.5.9
[INF] Created by Marcussacana
[INF] ExHIBIT Engine Detected.
[INF] SRL Initialized

**Comment by javiert239** [comment]
Quickly update.
I tried the new SRL tool in a fresh install of the game, and now the game works fine, but the SRL doesn't even generate the StringReloads folder.
If I rename the SRLWrapper.dll like d3d9.dll insteado SRLx32.dll, the StringReloads folder is genearated, but the games crashes.

**Comment by marcussacana** [comment]
I see, try open the game executable with a hex editor, find VERSION.DLL in the executable, then change to something with the same length, like SRL_x32.dll and rename the SRLWrapper to the new name, like SRL_x32.dll for example.
Then try start the game.
Also, enable the logfile and set loglevel to TRC, maybe will show the reason to crash.
the LogLevel TRC should create a more detailed log file

**Comment by javiert239** [comment]
Now the game start without issue, but the SRL doesn't generate the StringReloads folder, nor a logfile.

And by the way, the game only crashes when I change the name of the SRLWrapper to d3d9.dll.

**Comment by marcussacana** [comment]
try rename to dinput.dll or dxgi.dll as well.
Undo the VERSION.DLL changes in the executable as well.

**Comment by javiert239** [comment]
Done.
The same result, the game start without issue, but the SRL doesn't generate the StringReloads folder, nor a logfile.

**Comment by marcussacana** [comment]
Add me on Discord Marcus André#0956
