### ISSUE TITLE
Game Request: Koisuru Natsu no Last Resort & Sora to Umi ga, Fureau Kanata

### ISSUE THREAD

**Issue by Cerzs** [marcussacana/Specific-Games#4]
**Dev**: Pultop
**Releases**: [This for UmiKana](https://vndb.org/r56551) and [this for KoiRizo](https://vndb.org/r33197).

I need this type of _[chars](https://cdn.discordapp.com/attachments/475037213265100820/505256276717076490/Chars.txt)_.

Thank you.

**Comment by marcussacana** [comment]
Sure, I will just need a time because i'm working in other game now...
I supose in 7 days I can do it.
![image](https://user-images.githubusercontent.com/10576957/47547788-3aba8e00-d8cd-11e8-90e4-b91fa5315cec.png)

**Comment by Cerzs** [comment]
No problem, many thanks.

**Comment by marcussacana** [comment]
KoiRizo added, as extra, if you remove the ; in the SRL.ini (at the ReloadPrefix line),
you can make the game text small, after this just change in the SRL.ini the MaxWidth to fix the wordwrap
![https://up.vidyagam.es/abf437fe-1419-44ea-84a9-82d803361a36-AdvHD_2018-10-26_18-46-41.png](https://up.vidyagam.es/abf437fe-1419-44ea-84a9-82d803361a36-AdvHD_2018-10-26_18-46-41.png)
![https://up.vidyagam.es/021dbd70-5daa-4602-9bd6-9833be062c33-AdvHD_2018-10-26_18-46-26.png](https://up.vidyagam.es/021dbd70-5daa-4602-9bd6-9833be062c33-AdvHD_2018-10-26_18-46-26.png)

The other game you will need wait more a little, if I don't publish in 7 days back here to remember me.

**Comment by Cerzs** [comment]
Thank you! Working.

Is it possible to add these chars?
¡=ｷ
¿=ｱ
Ñ=ｰ
ñ=ｯ

**Comment by marcussacana** [comment]
Don't worked? 
The AdvHD with SRL becomes a utf-16 engine, don't need the chars.lst to works..

**Comment by Cerzs** [comment]
Oh, yes. It works. Sorry, I ignored that fact about UTF-16. 

I'm just new at this. Many thanks again.

**Comment by marcussacana** [comment]
Added

**Comment by Cerzs** [comment]
Thanks, really, works great. My friend will be pleased.

As for me, I have a doubt, you see, I like some Alice Soft titles, specifically [Rance 5D-??](https://vndb.org/v2046) and [Evenicle](https://vndb.org/r52349). It's possible to add this to Evenicle, for example? If so, can I request it?

Edit: I noticed that UmiKana .lst are in ANSI, is this intentional or can I change it to UTF-8 without breaking everything, @marcussacana?

**Comment by marcussacana** [comment]
Nop, in the true will be a problem if he is in ansi.
About the rance and evenicle, that engine uses a custom font format so the string reloader it's useless, don't exist texture of the characters like á é í ó...

**Comment by Cerzs** [comment]
I see. Well, thanks anyway! Keep up the good work!
