### ISSUE TITLE
Game Request: If You Love Me, Then Say So!

### ISSUE THREAD

**Issue by Cerzs** [marcussacana/Specific-Games#5]
**Dev**: ChuableSoft
**Release**: [This](https://vndb.org/r46904).

Hello again. Sorry if you're busy, a friend translator is interested in this one and even myself, haha.

Thank you.

**Comment by marcussacana** [comment]
I Will take a look soon, I have 2 games to work before your request.

**Comment by marcussacana** [comment]
Added.
But sorry, I can't get the wordwrap work (because this engine have they own breakline opcode), you will need manually test line per line or use an dissassembly tool.

**Comment by Cerzs** [comment]
Many thanks, @marcussacana. Btw, I'll request another one next year. Will be DameKoi, from MangaGamer, if it's not too much trouble. That'll be a personal project, though.

Thanks again.

**Comment by marcussacana** [comment]
I created this, https://github.com/marcussacana/MajiroStringEditor
I will test the stability yet, but will allow you break the line free without dissasembly the script.
