### ISSUE TITLE
Game Request & Doubt: Cross Channel Steam Edition

### ISSUE THREAD

**Issue by Cerzs** [marcussacana/Specific-Games#6]
Greetings!

Link: https://vndb.org/r56068

Same engine as KoiRizo and UmiKana. 

Now, we're interested in restoring the +18 content in the Steam version using [Final Complete](https://vndb.org/r35224), that would need great programming skills or there is a way to do it?

Thanks.

**Comment by marcussacana** [comment]
I Know how is a shit this censour but i never tried, I just know shitty method like adding the h-scene scripts and forcing the script before they to jump to the h-scene, this works, but will be a problem if the engine version is too different, the game can show problems with some effects, but isn't all cases.
To this isn't hard, as example:
Censoured Version:
```
Script_01.ws2 => Script_02.ws2
```
Uncensoured  Version:
```
Script_01.ws2 => Script_01h.ws2 => Script_02.ws2
```
What you can do:
Decrypt and open the Script_01.ws2 of the censoured version in a hex editor, go to at the end and replace the Script_02.ws2 with Script_1h.ws2 (try keep the same length).
Put the Script_01h.ws2 in the Rio.arc and rename to Script_1h.ws2.

Now when the game finish the Script_01.ws2 will jump to the Script_1h.ws2, and like originally the Script_1h.ws2 will jump to the Script_02.ws2 of the censoured version.

Don't just replace all ws2 files with the unc version because don't will work.

Well, Without study the ws2 format is what I can say, but is a 'wrong way' so, keep sure of test it before release anything.

About your request... well I will take a look soon, I don't recived a notification of this issue for some reason, I will wait you comment here to confirm if you still needing the tool.

**Comment by Cerzs** [comment]
Hello. Yes, I'm still interested.

I was checking the ws2 files but I couldn't find the name of the next file with 010 Editor.

**Comment by marcussacana** [comment]
The ws2 is encrypted, you can try this my tool to decrypt... https://github.com/marcussacana/WillPlusManager

To encrypt well:
https://github.com/marcussacana/WillPlusManager/blob/eebf43eeb343e632678345492e4533815b2fef49/WPMGUI/Form1.cs#L106-L106


Change this "Decrypt" to "Encrypt'"

**Comment by Cerzs** [comment]
Yes, I was using your tool. I thought was this.
![imagen](https://user-images.githubusercontent.com/44489935/54233071-87041480-44e2-11e9-992f-dc4ce2263d65.png)

**Comment by marcussacana** [comment]
Send me a script encrypted and decrypted.

**Comment by Cerzs** [comment]
[I used Decrypt with your tool](https://cdn.discordapp.com/attachments/529475786160472077/555125835095343135/CC_11A_en.zip), the file can't be opened now. Also, when I open a ws2, I can't open another without closing WPMGUI and opening it again, then choosing the file.

**Comment by marcussacana** [comment]
Fixed

**Comment by marcussacana** [comment]
Here is the next script probabbly, try changed it and play the h-scene to search for bugs,
don't forget to include the images and sounds used in the h-scene
![image](https://user-images.githubusercontent.com/10576957/54236470-588e3580-44f2-11e9-9b0c-c25fd6e5248e.png)

**Comment by Cerzs** [comment]
Decrypt working. I'll test that asap. Then all that remains is just the SRL for Unicode characters after this.

Thanks again for your time.

**Comment by marcussacana** [comment]
I will take a look now.
A hint, is possible to you make a 'optional' unc patch, if you create a subdirectory with any name, and copy the AdvHDLang.dll to this directory, just put any .arc and the game will read it optionally
The best part is you don't need put all files in the .arc, it's like a patch, just include modified files, because if the game don't found in the 'optional' directory, he will find in the original arc
![image](https://user-images.githubusercontent.com/10576957/54237837-a22c4f80-44f5-11e9-9704-e15de2be02a5.png)

**Comment by Cerzs** [comment]
Oh, that's really a great tip. Many thanks, I'll try!

**Comment by marcussacana** [comment]
Added.
Working like a charm~
![image](https://user-images.githubusercontent.com/10576957/54240081-d60a7380-44fb-11e9-98d4-bdd520174948.png)

**Comment by Cerzs** [comment]
I was checking the Final Complete version, it uses .cpk files. I think is not possible to use it with the Steam version.

**Comment by marcussacana** [comment]
Yeah, you will need a tool that can write ws2 scripts in this case, But I never saw one.
If is everything working, plz, close the issue.

**Comment by Cerzs** [comment]
@marcussacana I didn't want to open a new issue for the same engine, can you add [The Most Forbidden Love in the World ](https://vndb.org/r52352)?

**Comment by marcussacana** [comment]
I will take a look

**Comment by marcussacana** [comment]
@Cerzs the StringReloads isn't compatible with kirkiri games, but I think this can solve your problem.
[[MangaGamer] Forbidden Love with My Wife’s Sister [Data].rar](https://github.com/marcussacana/Specific-Games/files/3193558/MangaGamer.Forbidden.Love.with.My.Wife.s.Sister.Data.zip)

**Comment by marcussacana** [comment]
Can you give a link to download the game?
I downloaded the wrong title...

**Comment by Cerzs** [comment]
[Here](https://sukebei.nyaa.si/?f=0&c=0_0&q=sekai+de+ichiban+mangagamer). And they've released a [patch](https://t.co/5VO2risVVE?amp=1) for some typos, btw.

**Comment by marcussacana** [comment]
Added.

**Comment by Cerzs** [comment]
Hi there, @marcussacana. Just to let you know that it works perfect. But why these -- are appearing in-game when the translated line does not have it? 
![4F9kocp](https://user-images.githubusercontent.com/44489935/58228520-f70df280-7cfc-11e9-9748-88b969f32051.jpg)
![ffRFsbM](https://user-images.githubusercontent.com/44489935/58228542-08ef9580-7cfd-11e9-9d59-f798cc58c2d1.jpg)

**Comment by marcussacana** [comment]
hmm, check in the SRL.ini at "ReloadSufix" if have anything...
If don't fix, enable the LogAll, LogFile, and Debug values in the SRL.ini
and upload to me the SRL.log

**Comment by Cerzs** [comment]
[Here.](https://cdn.discordapp.com/attachments/505606567282999297/581004688535846961/SRL.log)

**Comment by marcussacana** [comment]
Hmm, strange, for now you can do the 'wrong way' that is put a match and replace to the SRL
Create a Replaces.lst and put this inside:
```
--
 
```

**Comment by Cerzs** [comment]
I'll try that. I was checking before, removing those -- from the original script (.ws2) also removes them from .lst, but too much work.

**Comment by marcussacana** [comment]
maybe you can try add in a .lst
```
{0}--
{0}
```
The SRL accept this type of thing, it's like a masked translation... as example:
`You have 9 potions left` can be translated in the SRL with:
```
You have {0} potions left
Você tem {0} poções restantes
```
Then you can use this feature to remove the -- too.

**Comment by Cerzs** [comment]
Hm, I tried but it does nothing, maybe I'm doing it wrong? I added it at the beginning of the file.

**Comment by marcussacana** [comment]
Well, no idea, the right thing is found from where this -- appears, if is in the original game script but not in the .lst, you can try add in the .lst

**Comment by Cerzs** [comment]
I'll try then. It's not a big deal anyway, you can close the issue.

Thanks for the help.

**Comment by Cerzs** [comment]
Hey, @marcussacana! Sorry about resurrecting an old issue, I just have a problem. You know this engine changes " for \d, yeah? But all .lst does not have them so is more comfortable. It would be too much effort adding it from scratch because the translation is already very far. 

Do you think that would be possible changing in the .ini this configuration or something? I want this:

Actual: "Hello." (\dHello.\d)
I want: "Hello".  (\dHello\d.) (Dot after ")

**Comment by marcussacana** [comment]
I don't get your problem, what you need? try explain again.

**Comment by Cerzs** [comment]
Ah! Sorry, I confused symbols. The engine uses \d as quotation marks. 

Example:

> \dIt'll help wake you up.\d

In-game would be:

> "It'll help wake you up."

But due to language rules, we need the dot after quotation marks. Like this:

> "It'll help wake you up".
> \dIt'll help wake you up\d.

**Comment by marcussacana** [comment]
you can't put the \d because the SRL is doing this automatically?

**Comment by Cerzs** [comment]
Yes, basically. Putting \d in the .lst would cause this:

> "It'll help wake you up.".

**Comment by marcussacana** [comment]
Wait, you are puting \d using the SRL.ini Prefix/Sufix?
Enable the LogFile and LogAll in your SRL.ini, start the game in the problematic dialogue, and upload your SRL.log, I can't get what are you trying do yet.

**Comment by Cerzs** [comment]
It's easy, look at this:

![imagen](https://user-images.githubusercontent.com/44489935/70599264-1b5eed00-1bc3-11ea-871f-701a86f4df64.png)

![imagen](https://user-images.githubusercontent.com/44489935/70599316-392c5200-1bc3-11ea-82f9-e23e860537ed.png)

As you can see, I don't have those \d that works as quotation marks.

**Comment by Cerzs** [comment]
Maybe because this?

![imagen](https://user-images.githubusercontent.com/44489935/70599508-a7711480-1bc3-11ea-97d1-92ebf167c90e.png)

**Comment by marcussacana** [comment]
Yeah, this can affect it... well
try do this:
put the \d in the english line and in the translation too.
Test if works, if show what the game display and the log in this part

**Comment by Cerzs** [comment]
[SRL.log](https://github.com/marcussacana/Specific-Games/files/3948944/SRL.log)

I get this:
![imagen](https://user-images.githubusercontent.com/44489935/70600313-c83a6980-1bc5-11ea-80e6-72729318e78b.png)

Also yes 

> 3:24 a. m.: [D|-1] Input: \dSo now it's going to snow, too? Ugh...!\d%K%P
3:24 a. m.: Trim Request:
Ori: \dSo now it's going to snow, too? Ugh...!\d%K%P
Str: \d¿Entonces ahora también va a nevar? ¡Ugh...!\d.
3:24 a. m.: Trim Result: \d¿Entonces ahora también va a nevar? ¡Ugh...!\d.\d%K%P
3:24 a. m.: Output: \d¿Entonces ahora también va a nevar? ¡Ugh...!\d.\d%K%P

Edit: theoretically, removing the \d from trim list fix this, I'll figure out how to add it to dialogues without too much effort.

**Comment by marcussacana** [comment]
You don't need do manually, I think I can add a manual feature to solve your case, just a sec.

**Comment by marcussacana** [comment]
I published a update, try add `::NOTRIM::` in the begin of the translation line in the .lst,  
then manually put the \d in the translation line.

**Comment by Cerzs** [comment]
It's ignoring the command, I guess:

![imagen](https://user-images.githubusercontent.com/44489935/70602578-2289f900-1bcb-11ea-96bd-569f64f05b53.png)

It's ok? 

![imagen](https://user-images.githubusercontent.com/44489935/70602634-39c8e680-1bcb-11ea-9f99-1a8970e86e22.png)

Btw, no LogAll in this version? Or just a name change?

**Comment by marcussacana** [comment]
Yeah, I changed to Verbose, I think it's a better name for this option.

**Comment by marcussacana** [comment]
It's okay, just test it and show the log in this part if don't work.

**Comment by Cerzs** [comment]
Got it working but... 

Modified lines (No command):
> \dU... Ugh... Ghg... Ah...?\d
\dU-Ugh... Ghg... ¿Ah...?\d.

Result:
![imagen](https://user-images.githubusercontent.com/44489935/70603297-98429480-1bcc-11ea-8141-c908112fe511.png)

Modified lines (With ::NOTRIM::):

> \dU... Ugh... Ghg... Ah...?\d
::NOTRIM::\dU-Ugh... Ghg... ¿Ah...?\d.

Result: 
![imagen](https://user-images.githubusercontent.com/44489935/70603378-d049d780-1bcc-11ea-9573-31507db9ea4f.png)

It's merging the next line?

**Comment by marcussacana** [comment]
Man, screenshot don't give me enough details, when you want me to see the reason of a problem, always provide the log.

**Comment by Cerzs** [comment]
Sorry about that, I was checking one last time before send it. I'm going to sleep because almost 5 am here. Maybe you can check by yourself when you have time, don't worry about it.

[SRL.log](https://github.com/marcussacana/Specific-Games/files/3949140/SRL.log)

**Comment by marcussacana** [comment]
try again with the last.

**Comment by Cerzs** [comment]
Same thing, working but merging the next line.

[SRL.log](https://github.com/marcussacana/Specific-Games/files/3949248/SRL.log)

**Comment by marcussacana** [comment]
Strange, I think i will need download the game and see by me self,
you can do the first working method fine, but if you want me to fix that send to my email your problematic .lst, a save game and a link to me download the game.

But one thing before, you removed the \d from the trimlist before, but you added it again to test the ::NOTRIM:: ?

**Comment by marcussacana** [comment]
ohh, include your srl.ini too

**Comment by Cerzs** [comment]
@marcussacana Yes, I included it and same. But yeah, I can use the first method easy, so no problem. A last question before closing this, would it be possible to change the windows title through SRL? 

![imagen](https://user-images.githubusercontent.com/44489935/70645459-6d336180-1c1b-11ea-9d03-3a05564f6409.png)

**Comment by marcussacana** [comment]
try enable this 
![image](https://user-images.githubusercontent.com/10576957/70647493-d1f4b900-1c27-11ea-9500-48016bb23208.png)

**Comment by Cerzs** [comment]
Ah, nope, it doesn't hook. Maybe because the title is in a .lua?

**Comment by marcussacana** [comment]
You take a look if he display the text in the log?

**Comment by Cerzs** [comment]
[SRL.log](https://github.com/marcussacana/Specific-Games/files/3952336/SRL.log)

Just this or similars

> 4:10 p. m.: [D|-1] Input: Chapter 1 - Prologue

I tried the decrypt option from Willplus manager, but no luck. 
[Script.arc~.zip](https://github.com/marcussacana/Specific-Games/files/3952360/Script.arc.zip)

**Comment by marcussacana** [comment]
Upload this game exe to me.

**Comment by Cerzs** [comment]
[AdvHD.zip](https://github.com/marcussacana/Specific-Games/files/3952616/AdvHD.zip)

**Comment by marcussacana** [comment]
try enable the SetWindowText in the srl.ini

**Comment by Cerzs** [comment]
I just managed to change the config title, is the configuration that opens before the game. 
[SRL.log](https://github.com/marcussacana/Specific-Games/files/3952809/SRL.log)

![imagen](https://user-images.githubusercontent.com/44489935/70664480-d8dbf580-1c40-11ea-8c69-1faf9bb4c72b.png)

Edit: Yep, only catch the configuration window, maybe the game only read those .lua...

![imagen](https://user-images.githubusercontent.com/44489935/70665012-f9587f80-1c41-11ea-83e2-e49a25d3d7b1.png)

**Comment by marcussacana** [comment]
I see... maybe is a problem with the handler cache then...
Test a thing to me, the AdvHD allow skip this config window, try skip it and see if you will can translate the title of the game window after that.

**Comment by Cerzs** [comment]
Tested, nothing. 

Edit: Do you know how to restart the config window? I was looking for a cache file, but nothing.

**Comment by marcussacana** [comment]
he don't store the cache in your disk, it's in the memory when the game starts, to solve your problem he need dispose the cache after config window close, but the SRL didn't expected 2 windows to the game.

**Comment by marcussacana** [comment]
Well, I think is more easy you edit the .exe manually or the .ws2...

**Comment by Cerzs** [comment]
Welp, thanks anyway.

Edit: This doesn't have anything to do with it, but the LST generator does not extract the names 

![imagen](https://user-images.githubusercontent.com/44489935/70740368-60803d80-1cef-11ea-996e-de6a302b2af3.png)

![imagen](https://user-images.githubusercontent.com/44489935/70740389-70981d00-1cef-11ea-97cb-d9c6b161703d.png)

**Comment by marcussacana** [comment]
Maybe is your filter settings in the .ini of the LST generator.

**Comment by Cerzs** [comment]
Do you have an example?

>[Filter]
;DenyList=@\n§\n$\n_\n<\n>\n/\n[\n]\n\
;QuoteList=<>\n()\n[]\n“”\n［］\n《》\n«»\n「」\n『』\n【】\n（）\n''\n""
IgnoreList=_
TrimList= 
Sensitivity=3
AsianInput=false
Filter=false

**Comment by marcussacana** [comment]
hmm, is already disable, then not sure why, maybe you don't used the -Dump.bat to generate the lst?

**Comment by Cerzs** [comment]
@marcussacana I tried all. Maybe you could try it.

[ws2.zip](https://github.com/marcussacana/Specific-Games/files/3959414/ws2.zip)

**Comment by marcussacana** [comment]
you have sure the plugin is updated?

**Comment by Cerzs** [comment]
I tried a fresh install from Plugin Manager.

**Comment by marcussacana** [comment]
try open the WillPlusManager.ini and replace the file text with this:
```ini
[Plugin]
Import=WillPlusManager.WS2Helper>Import
Export=WillPlusManager.WS2Helper>Export
Extensions=WS2
Initialize=true
```
Looks like It's outdated...? 
If don't dump any .ws2 after you edit, try copy the .dll from the WMGUI to the Plugins directory manually

**Comment by Cerzs** [comment]
Yep, it looks like was outdated. Fixed, thank you! And sorry for all the trouble!

**Comment by marcussacana** [comment]
You edited the .ini only or copied the dll to works too?

**Comment by Cerzs** [comment]
I edited the .ini then copied the .dll
