### ISSUE TITLE
Game Request: Yumekoi Tensei

### ISSUE THREAD

**Issue by sakurahana90** [marcussacana/Specific-Games#7]
Hello, I don't know if this's the right place to ask this, I tried using Stringreload to edit the script of Tinkerbell's game, Yumekoi Tensei but after injecting the exe, I didn't find any string.lst to edit after I ran the game. I need some help, does stringreload support this kind of engine?

You can find the example of exe and script in the patch on their site: http://www.cyberworks.jp/tink_nanigashi/tensei/dl.html

**Comment by marcussacana** [comment]
The SRL isn't a automatic tool, just inject the dll don't will help much, you need modify the engine and 'proxy' the script with the SRL, then run the game with the SRL in the Debug mode and he will dump the Strings.lst

**Comment by sakurahana90** [comment]
what tool used to modify the engine? Is it about inserting the command before original script to link the game with SRL, like what's written in the readme? I don't know how to to that...

**Comment by marcussacana** [comment]
Yeah it's this, the SRL isn't easy to use.

**Comment by marcussacana** [comment]
Well man, I tried but this engine have a specified string length, and the SRL only support null-terminated strings, then if we use the SRL in engines like of this we can see many bugs.
![image](https://user-images.githubusercontent.com/10576957/68978471-9c4fe200-07d9-11ea-8eae-6d8cf49bb73b.png)
So it's this...
