### ISSUE TITLE
Game Request:  Kizuna Kirameku Koi Iroha

### ISSUE THREAD

**Issue by imKota** [marcussacana/Specific-Games#8]

**Comment by marcussacana** [comment]
what engine?

**Comment by imKota** [comment]
@marcussacana i think it's SOFTPAL_ADV_SYSTEM
I found [tools](https://github.com/Yggdrasill-Moe/Niflheim/tree/master/SOFTPAL_ADV_SYSTEM) . but pac_text.py not working
[tool.zip](https://github.com/marcussacana/Specific-Games/files/3341323/tool.zip)

**Comment by marcussacana** [comment]
try this one
https://github.com/marcussacana/UnisonShiftManager
They can edit the text.dat but don't update any offsets, you need manually update the text offset in the script.src, this is complex

**Comment by imKota** [comment]
@marcussacana 

> you need manually update the text offset in the script.src

Yes, I know it.

> this is complex

You do not know how to do this?

**Comment by marcussacana** [comment]
A Little but I never did, because I use my string reloader to inject the text direct in the game memory

**Comment by imKota** [comment]
> because I use my string reloader to inject the text direct in the game memory

Is it hard to use?
It would be nice if there was an example of use.

**Comment by imKota** [comment]
Can you help me with unpack and repack this file ?
DEFAULT_FONT.DAT
[DEFAULT_FONT.zip](https://github.com/marcussacana/Specific-Games/files/3441059/DEFAULT_FONT.zip)

Since the fonts are in this file, changing the fonts by this method:
```

PVOID g_pOldCreateFontIndirectW = CreateFontIndirectW;
typedef HFONT (WINAPI *PfuncCreateFontIndirectW)(LOGFONTW *lplf);
HFONT WINAPI NewCreateFontIndirectW(LOGFONTW *lplf)
{
	lplf->lfCharSet = ANSI_CHARSET;

        if (!wcscmp(lplf->lfFaceName, L"ＭＳ 明朝"))
	{
		wcscpy(lplf->lfFaceName, L"MyFont");
	}
	else if (!wcscmp(lplf->lfFaceName, L"ＭＳ ゴシック"))
	{
		wcscpy(lplf->lfFaceName, L"MyFont");
	}

	return ((PfuncCreateFontIndirectW)g_pOldCreateFontIndirectW)(lplf);
}

```
Does not work.

![image](https://user-images.githubusercontent.com/24241471/62033953-c31be580-b1f5-11e9-940a-8caa0e3add61.png)

**Comment by imKota** [comment]
@marcussacana hello!
Can you help me with unpack and repack this file ?
DEFAULT_FONT.DAT
[DEFAULT_FONT.zip](https://github.com/marcussacana/Specific-Games/files/3441059/DEFAULT_FONT.zip)

Since the fonts are in this file, changing the fonts by this method:
```

PVOID g_pOldCreateFontIndirectW = CreateFontIndirectW;
typedef HFONT (WINAPI *PfuncCreateFontIndirectW)(LOGFONTW *lplf);
HFONT WINAPI NewCreateFontIndirectW(LOGFONTW *lplf)
{
	lplf->lfCharSet = ANSI_CHARSET;

        if (!wcscmp(lplf->lfFaceName, L"ＭＳ 明朝"))
	{
		wcscpy(lplf->lfFaceName, L"MyFont");
	}
	else if (!wcscmp(lplf->lfFaceName, L"ＭＳ ゴシック"))
	{
		wcscpy(lplf->lfFaceName, L"MyFont");
	}

	return ((PfuncCreateFontIndirectW)g_pOldCreateFontIndirectW)(lplf);
}

```
Does not work.

![image](https://user-images.githubusercontent.com/24241471/62033953-c31be580-b1f5-11e9-940a-8caa0e3add61.png)

**Comment by marcussacana** [comment]
You tried delete this default font file from the game?
Some engines like kirikiri when have the embed font deleted automatically load a system font.

**Comment by imKota** [comment]
> You tried delete this default font file from the game?
> Some engines like kirikiri when have the embed font deleted automatically load a system font.

wtf

![image](https://user-images.githubusercontent.com/24241471/62073554-9e515d80-b249-11e9-9858-9f1f530b3e8c.png)

**Comment by marcussacana** [comment]
Don't care, this is a good signal, this font is easy to edit.

**Comment by imKota** [comment]
> Don't care, this is a good signal, this font is easy to edit.

How ?
The first time I come across this font

**Comment by marcussacana** [comment]
Crystaltile2 or tilemolester tool can open this maybe

**Comment by imKota** [comment]
> Crystaltile2 or tilemolester tool can open this maybe

don't open:D

**Comment by marcussacana** [comment]
You tried all avaliable formats?, in your screenshot looks like it's 8bpp or 4bpp

**Comment by imKota** [comment]
> You tried all avaliable formats?, in your screenshot looks like it's 8bpp or 4bpp

![image](https://user-images.githubusercontent.com/24241471/62076017-52091c00-b24f-11e9-990e-d697f9643de0.png)

I think I can not translate this novel .. since the font I can not figure it out ...

**Comment by marcussacana** [comment]
You need fix the color table in the bottom part of the screenshot, just use black/gray and white colors.
And the pixel format you selected don't looks the right one yet.
