### ISSUE TITLE
Game Request: Trinoline

### ISSUE THREAD

**Issue by Gygarde** [marcussacana/Specific-Games#9]
Hi. Do you know if is possible to add SRL to [Trinoline](https://vndb.org/r46953)? Or if there is a tool that can help with that engine + font.

**Comment by marcussacana** [comment]
I have others game to work yet, when I have a free time i will notify you here.

**Comment by Gygarde** [comment]
'Kay. Thank you very much.

**Comment by imKota** [comment]
> Hi. Do you know if is possible to add SRL to [Trinoline](https://vndb.org/r46953)? Or if there is a tool that can help with that engine + font.

Hello, @Gygarde 
I working with Trinoline. What do you need help with? And what language do you plan to translate?

**Comment by Gygarde** [comment]
Hi, @imKota!

I want to translate it into Spanish. But I really don't know much about unpacking/repacking minori files. I also don't know if the accents will work.

**Comment by imKota** [comment]
@Gygarde do you have discord?

**Comment by Gygarde** [comment]
Yes, but I'm not at home. If you can, give me your user and I can tell the admin, so he can add you.

**Comment by imKota** [comment]
@Gygarde Kota#1914

**Comment by marcussacana** [comment]
If you keep wanting the SRL support you can reopen the issue at any time.
